version: '3.7'
name: e2e
services:
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: e2e_auth
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5433
  auth-redis:
    image: redis:latest
    ports:
      - 6380:6380
  auth-server:
    build: .
    ports:
      - 4001:4001
    environment:
      - JWT_SECRET=ThisIsTheJWTSecret
      - DB_DEV_USER=postgres
      - DB_DEV_HOST=auth-db
      - DB_DEV_NAME=e2e_auth
      - DB_DEV_PASSWORD=postgres
      - DB_DEV_PORT=5433
      - REDIS_HOST=auth-redis
      - REDIS_PORT=6380
      - DB_TEST_USER=postgres
      - DB_TEST_NAME=e2e_auth
      - DB_TEST_HOST=auth-db
      - DB_TEST_PORT=5433